import './globals.css'

import { Electrolize } from 'next/font/google'
import StyledComponentsRegistry from '../lib/AntdRegistry';

const electrolize = Electrolize({ weight: "400", subsets: ['latin'] })

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

import connectMongoDB from './utils/connectDb';

config.autoAddCss = false;

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  connectMongoDB();
  return (
    <html lang="en">
      <body className={electrolize.className}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  )
}